# Generated by Django 4.2.16 on 2025-07-21 23:27

import apps.blog.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_heading_post_alter_postview_post_postanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
